"""Abstract base class that every connector must implement."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ConnectorMetadata:
    key: str
    name: str
    category: str  # crm | workspace | meetings
    auth_type: str  # oauth2 | api_key
    scope: str  # org | user
    description: str = ""
    icon_url: str = ""
    oauth_scopes: list[str] = field(default_factory=list)
    oauth_config: dict = field(default_factory=dict)


class BaseConnector(ABC):
    """
    All connectors inherit from this class.
    Each subclass must declare a `metadata` class attribute.
    """

    metadata: ConnectorMetadata

    # ------------------------------------------------------------------
    # OAuth lifecycle
    # ------------------------------------------------------------------

    @abstractmethod
    async def get_oauth_url(self, state: str, redirect_uri: str) -> str:
        """
        Return the authorization URL to redirect the user to for OAuth consent.
        `state` is an opaque value generated by the caller to prevent CSRF.
        """

    @abstractmethod
    async def exchange_code(self, code: str, redirect_uri: str) -> dict[str, Any]:
        """
        Exchange an authorization code for access/refresh tokens.
        Returns a dict with at minimum: access_token, refresh_token (optional),
        expires_in (seconds), token_type, scope.
        """

    @abstractmethod
    async def refresh_token(self, credentials: dict[str, Any]) -> dict[str, Any]:
        """
        Use the refresh_token in `credentials` to obtain a new access token.
        Returns the same shape as exchange_code.
        """

    @abstractmethod
    async def test_connection(self, credentials: dict[str, Any]) -> bool:
        """
        Make a lightweight authenticated API call to verify the credentials work.
        Returns True if successful.
        """

    # ------------------------------------------------------------------
    # Data retrieval (used by the AI orchestrator)
    # ------------------------------------------------------------------

    @abstractmethod
    async def fetch_data(self, credentials: dict[str, Any], query: str) -> dict[str, Any]:
        """
        Fetch relevant data from the third-party API based on a natural-language query.
        The AI service calls this method; the connector decides how to interpret `query`.
        Returns a dict with `results` (list) and optional `metadata`.
        """

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def to_seed_dict(self) -> dict:
        """Return a dict suitable for seeding the `connectors` DB table."""
        m = self.metadata
        return {
            "key": m.key,
            "name": m.name,
            "category": m.category,
            "auth_type": m.auth_type,
            "description": m.description,
            "icon_url": m.icon_url,
            "oauth_config": {
                "scopes": m.oauth_scopes,
                **m.oauth_config,
            },
            "is_available": True,
        }
